name: Fast-API CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  dockerhub_id: Tatapong
  dockerhub_repository: fastapi
  dockerhub_latest: latest

jobs:
  secure:
    name: Microsoft Security DevOps Analysis
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Microsoft Security DevOps Analysis
        uses: microsoft/security-devops-action@latest
        id: msdo
        with:
          policy: 'GitHub'
      - name: Upload alerts to Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.msdo.outputs.sarifFile }}
      - name: Upload alerts file as a workflow artifact
        uses: actions/upload-artifact@v3
        with:  
          name: alerts
          path: ${{ steps.msdo.outputs.sarifFile }}
        
  build-push-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          # Build the Docker image with a commit-specific tag
          docker build -t $dockerhub_id/$dockerhub_repository:${GITHUB_SHA} .
          # Tag the image with the "latest" tag
          docker tag $dockerhub_id/$dockerhub_repository:${GITHUB_SHA} $dockerhub_id/$dockerhub_repository:$dockerhub_latest
          # Display the Docker images available locally
          docker images
          # Run the Docker image locally for testing
          docker run -d -p 80:80 --name $dockerhub_repository $dockerhub_id/$dockerhub_repository:${GITHUB_SHA}
          sleep 10
          # Test t
